# config.yaml
dataset: FractionalBrownianMotion
epoch:   30
model: transformer
global_backward: true
num_windows: 50
n_head: 3
sig_level: 4
add_time: true
irreg: true
univariate: true
lr: 0.001
use_signatures: true
online_signature_calc: true